# Generated by Django 4.2.6 on 2023-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uuid', models.UUIDField()),
                ('asin', models.CharField(max_length=255)),
                ('product_image_url', models.URLField()),
                ('product_detail', models.TextField()),
            ],
        ),
    ]
